### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by WuRAFY** [MathOnco/NeoPredPipe#42]
Thanks for the tool! I'm using docker version of NeoPredPipe, but I met the same error as #17.

```
Traceback (most recent call last):
  File "/software/NeoPredPipe-1.1/NeoPredPipe.py", line 523, in <module>
    main()
  File "/software/NeoPredPipe-1.1/NeoPredPipe.py", line 504, in main
    t.append(Sample(localpath, patname, patFile, hlas[patname], annPaths, netMHCpanPaths, pepmatchPaths, Options))
  File "/software/NeoPredPipe-1.1/NeoPredPipe.py", line 105, in __init__
    self.callNeoantigens(FilePath, netmhcpan, Options)
  File "/software/NeoPredPipe-1.1/NeoPredPipe.py", line 150, in callNeoantigens
    self.peptideFastas = MakeTempFastas(self.fastaChangeFormat, Options.epitopes)
  File "/software/NeoPredPipe-1.1/vcf_manipulate.py", line 147, in MakeTempFastas
    pos = int(seq_record.id.replace(";;",";").split(";")[6].split('-')[0])-1
IndexError: list index out of range

```

Can you please update docker version of the tool? Much thanks

**Comment by elakatos** [comment]
Thanks for the feedback, I'll update in the coming days!
