### ISSUE TITLE
NeoRecoPo.py error

### ISSUE THREAD

**Issue by h170607** [MathOnco/NeoPredPipe#44]
> Traceback (most recent call last):
>    File "/data/yanr/script/neoantigen/NeoPredPipe-1.1/NeoRecoPo.py", line 135, in <module>
>      main()
>    File "/data/yanr/script/neoantigen/NeoPredPipe-1.1/NeoRecoPo.py", line 124, in main
>      preds.PerformCalculations(tmpOut, Options)
>    File "/data/yanr/script/neoantigen/NeoPredPipe-1.1/StandardPredsClass.py", line 479, in PerformCalculations
>      [neoantigens, samples] = self._compileNeoantigens(neofile, Options.Indels)
>    File "/data/yanr/script/neoantigen/NeoPredPipe-1.1/StandardPredsClass.py", line 455, in _compileNeoantigens
>      neoantigen = Neoantigen(nparams, indels)
>    File "/data/yanr/script/neoantigen/NeoPredPipe-1.1/NeoClass.py", line 60, in __init__
>      [res1, res2] = filter(lambda el: el[0] != el[1], zip(self.wtPeptide, self.mtPeptide))[0]
>  TypeError: 'filter' object is not subscriptable

The columns names of my vcf files are as follows:

> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  tumor       normal

The command is:
`python3 /data/script/neoantigen/NeoPredPipe-1.1/NeoPredPipe.py -I ./vcfs -H ./hlas.txt -o ./ -n TestRun -c 0 -E 8 9 10 -d`
`python3 /data/script/neoantigen/NeoPredPipe-1.1/NeoRecoPo.py --neopred_in TestRun.neoantigens.txt --neoreco_out ./reco --fastas ./fastaFiles`

**Comment by h170607** [comment]
we used python 2 instead, and it worked, according to #39
