### ISSUE TITLE
Docker update

### ISSUE THREAD

**Issue by RTCarmo** [MathOnco/NeoPredPipe#50]
Hello,

Do you plan to update the docker image of NeoPredPipe?

Thanks,
Ramon

**Comment by RTCarmo** [comment]
Also, related to the docker image... After some changes in the server on which I run NeoPredPipe, I decided to try your docker image. I am trying to run NeoRecoPO.py for the first time, and after a while, I got the following error:

`Traceback (most recent call last):
  File "/src/NeoPredPipe/NeoRecoPo.py", line 135, in <module>
    main()
  File "/src/NeoPredPipe/NeoRecoPo.py", line 101, in main
    preds.BuildFinalTable(Options.Indels)
  File "/src/NeoPredPipe/StandardPredsClass.py", line 321, in BuildFinalTable
    wtPred = wildtypeDict[mutKey]
KeyError: 'ROP-70,5,HLA-B*50:01,6226,9'
`

In the log file, everything seems normal:

> INFO: Begin.
> INFO: Neoantigen predictions already complete for ROP-33 epitopes of length 9
> INFO: Predicting neoantigens for ROP-32
> INFO: Running Epitope Predictions for ROP-32 on epitopes of length 9
> INFO: Predictions complete for ROP-32 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-37
> INFO: Running Epitope Predictions for ROP-37 on epitopes of length 9
> INFO: Predictions complete for ROP-37 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-36
> INFO: Running Epitope Predictions for ROP-36 on epitopes of length 9
> INFO: Predictions complete for ROP-36 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-34
> INFO: Running Epitope Predictions for ROP-34 on epitopes of length 9
> INFO: Predictions complete for ROP-34 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-38
> INFO: Running Epitope Predictions for ROP-38 on epitopes of length 9
> INFO: Predictions complete for ROP-38 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-15
> INFO: Running Epitope Predictions for ROP-15 on epitopes of length 9
> INFO: Predictions complete for ROP-15 on epitopes of length 9
> INFO: Neoantigen predictions already complete for ROP-61 epitopes of length 9
> INFO: Predicting neoantigens for ROP-19
> INFO: Running Epitope Predictions for ROP-19 on epitopes of length 9
> INFO: Predictions complete for ROP-19 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-54
> INFO: Running Epitope Predictions for ROP-54 on epitopes of length 9
> INFO: Predictions complete for ROP-54 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-57
> INFO: Running Epitope Predictions for ROP-57 on epitopes of length 9
> INFO: Predictions complete for ROP-57 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-56
> INFO: Running Epitope Predictions for ROP-56 on epitopes of length 9
> INFO: Predictions complete for ROP-56 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-51
> INFO: Running Epitope Predictions for ROP-51 on epitopes of length 9
> INFO: Predictions complete for ROP-51 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-50
> INFO: Running Epitope Predictions for ROP-50 on epitopes of length 9
> INFO: Predictions complete for ROP-50 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-53
> INFO: Running Epitope Predictions for ROP-53 on epitopes of length 9
> INFO: Predictions complete for ROP-53 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-90
> INFO: Running Epitope Predictions for ROP-90 on epitopes of length 9
> INFO: Predictions complete for ROP-90 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-11
> INFO: Running Epitope Predictions for ROP-11 on epitopes of length 9
> INFO: Predictions complete for ROP-11 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-76
> INFO: Running Epitope Predictions for ROP-76 on epitopes of length 9
> INFO: Predictions complete for ROP-76 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-75
> INFO: Running Epitope Predictions for ROP-75 on epitopes of length 9
> INFO: Predictions complete for ROP-75 on epitopes of length 9
> INFO: Neoantigen predictions already complete for ROP-12 epitopes of length 9
> INFO: Predicting neoantigens for ROP-73
> INFO: Running Epitope Predictions for ROP-73 on epitopes of length 9
> INFO: Predictions complete for ROP-73 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-14
> INFO: Running Epitope Predictions for ROP-14 on epitopes of length 9
> INFO: Predictions complete for ROP-14 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-17
> INFO: Running Epitope Predictions for ROP-17 on epitopes of length 9
> INFO: Predictions complete for ROP-17 on epitopes of length 9
> INFO: Neoantigen predictions already complete for ROP-70 epitopes of length 9
> INFO: Predicting neoantigens for ROP-1
> INFO: Running Epitope Predictions for ROP-1 on epitopes of length 9
> INFO: Predictions complete for ROP-1 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-121
> INFO: Running Epitope Predictions for ROP-121 on epitopes of length 9
> INFO: Predictions complete for ROP-121 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-122
> INFO: Running Epitope Predictions for ROP-122 on epitopes of length 9
> INFO: Predictions complete for ROP-122 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-109
> INFO: Running Epitope Predictions for ROP-109 on epitopes of length 9
> INFO: Predictions complete for ROP-109 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-125
> INFO: Running Epitope Predictions for ROP-125 on epitopes of length 9
> INFO: Predictions complete for ROP-125 on epitopes of length 9
> INFO: Neoantigen predictions already complete for ROP-126 epitopes of length 9
> INFO: Predicting neoantigens for ROP-127
> INFO: Running Epitope Predictions for ROP-127 on epitopes of length 9
> INFO: Predictions complete for ROP-127 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-128
> INFO: Running Epitope Predictions for ROP-128 on epitopes of length 9
> INFO: Predictions complete for ROP-128 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-129
> INFO: Running Epitope Predictions for ROP-129 on epitopes of length 9
> INFO: Predictions complete for ROP-129 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-100
> INFO: Running Epitope Predictions for ROP-100 on epitopes of length 9
> INFO: Predictions complete for ROP-100 on epitopes of length 9
> INFO: Neoantigen predictions already complete for ROP-107 epitopes of length 9
> INFO: Predicting neoantigens for ROP-105
> INFO: Running Epitope Predictions for ROP-105 on epitopes of length 9
> INFO: Predictions complete for ROP-105 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-119
> INFO: Running Epitope Predictions for ROP-119 on epitopes of length 9
> INFO: Predictions complete for ROP-119 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-83
> INFO: Running Epitope Predictions for ROP-83 on epitopes of length 9
> INFO: Predictions complete for ROP-83 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-86
> INFO: Running Epitope Predictions for ROP-86 on epitopes of length 9
> INFO: Predictions complete for ROP-86 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-71
> INFO: Running Epitope Predictions for ROP-71 on epitopes of length 9
> INFO: Predictions complete for ROP-71 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-85
> INFO: Running Epitope Predictions for ROP-85 on epitopes of length 9
> INFO: Predictions complete for ROP-85 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-16
> INFO: Running Epitope Predictions for ROP-16 on epitopes of length 9
> INFO: Predictions complete for ROP-16 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-78
> INFO: Running Epitope Predictions for ROP-78 on epitopes of length 9
> INFO: Predictions complete for ROP-78 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-24
> INFO: Running Epitope Predictions for ROP-24 on epitopes of length 9
> INFO: Predictions complete for ROP-24 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-120
> INFO: Running Epitope Predictions for ROP-120 on epitopes of length 9
> INFO: Predictions complete for ROP-120 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-20
> INFO: Running Epitope Predictions for ROP-20 on epitopes of length 9
> INFO: Predictions complete for ROP-20 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-59
> INFO: Running Epitope Predictions for ROP-59 on epitopes of length 9
> INFO: Predictions complete for ROP-59 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-23
> INFO: Running Epitope Predictions for ROP-23 on epitopes of length 9
> INFO: Predictions complete for ROP-23 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-96
> INFO: Running Epitope Predictions for ROP-96 on epitopes of length 9
> INFO: Predictions complete for ROP-96 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-46
> INFO: Running Epitope Predictions for ROP-46 on epitopes of length 9
> INFO: Predictions complete for ROP-46 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-108
> INFO: Running Epitope Predictions for ROP-108 on epitopes of length 9
> INFO: Predictions complete for ROP-108 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-60
> INFO: Running Epitope Predictions for ROP-60 on epitopes of length 9
> INFO: Predictions complete for ROP-60 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-47
> INFO: Running Epitope Predictions for ROP-47 on epitopes of length 9
> INFO: Predictions complete for ROP-47 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-44
> INFO: Running Epitope Predictions for ROP-44 on epitopes of length 9
> INFO: Predictions complete for ROP-44 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-123
> INFO: Running Epitope Predictions for ROP-123 on epitopes of length 9
> INFO: Predictions complete for ROP-123 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-42
> INFO: Running Epitope Predictions for ROP-42 on epitopes of length 9
> INFO: Predictions complete for ROP-42 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-65
> INFO: Running Epitope Predictions for ROP-65 on epitopes of length 9
> INFO: Predictions complete for ROP-65 on epitopes of length 9
> INFO: Neoantigen predictions already complete for ROP-68 epitopes of length 9
> INFO: Predicting neoantigens for ROP-69
> INFO: Running Epitope Predictions for ROP-69 on epitopes of length 9
> INFO: Predictions complete for ROP-69 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-133
> INFO: Running Epitope Predictions for ROP-133 on epitopes of length 9
> INFO: Predictions complete for ROP-133 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-132
> INFO: Running Epitope Predictions for ROP-132 on epitopes of length 9
> INFO: Predictions complete for ROP-132 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-131
> INFO: Running Epitope Predictions for ROP-131 on epitopes of length 9
> INFO: Predictions complete for ROP-131 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-89
> INFO: Running Epitope Predictions for ROP-89 on epitopes of length 9
> INFO: Predictions complete for ROP-89 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-58
> INFO: Running Epitope Predictions for ROP-58 on epitopes of length 9
> INFO: Predictions complete for ROP-58 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-118
> INFO: Running Epitope Predictions for ROP-118 on epitopes of length 9
> INFO: Predictions complete for ROP-118 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-45
> INFO: Running Epitope Predictions for ROP-45 on epitopes of length 9
> INFO: Predictions complete for ROP-45 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-18
> INFO: Running Epitope Predictions for ROP-18 on epitopes of length 9
> INFO: Predictions complete for ROP-18 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-115
> INFO: Running Epitope Predictions for ROP-115 on epitopes of length 9
> INFO: Predictions complete for ROP-115 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-114
> INFO: Running Epitope Predictions for ROP-114 on epitopes of length 9
> INFO: Predictions complete for ROP-114 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-117
> INFO: Running Epitope Predictions for ROP-117 on epitopes of length 9
> INFO: Predictions complete for ROP-117 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-116
> INFO: Running Epitope Predictions for ROP-116 on epitopes of length 9
> INFO: Predictions complete for ROP-116 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-110
> INFO: Running Epitope Predictions for ROP-110 on epitopes of length 9
> INFO: Predictions complete for ROP-110 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-113
> INFO: Running Epitope Predictions for ROP-113 on epitopes of length 9
> INFO: Predictions complete for ROP-113 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-112
> INFO: Running Epitope Predictions for ROP-112 on epitopes of length 9
> INFO: Predictions complete for ROP-112 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-102
> INFO: Running Epitope Predictions for ROP-102 on epitopes of length 9
> INFO: Predictions complete for ROP-102 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-93
> INFO: Running Epitope Predictions for ROP-93 on epitopes of length 9
> INFO: Predictions complete for ROP-93 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-92
> INFO: Running Epitope Predictions for ROP-92 on epitopes of length 9
> INFO: Predictions complete for ROP-92 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-95
> INFO: Running Epitope Predictions for ROP-95 on epitopes of length 9
> INFO: Predictions complete for ROP-95 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-94
> INFO: Running Epitope Predictions for ROP-94 on epitopes of length 9
> INFO: Predictions complete for ROP-94 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-97
> INFO: Running Epitope Predictions for ROP-97 on epitopes of length 9
> INFO: Predictions complete for ROP-97 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-103
> INFO: Running Epitope Predictions for ROP-103 on epitopes of length 9
> INFO: Predictions complete for ROP-103 on epitopes of length 9
> INFO: Predicting neoantigens for ROP-98
> INFO: Running Epitope Predictions for ROP-98 on epitopes of length 9
> INFO: Predictions complete for ROP-98 on epitopes of length 9
> INFO: Digesting neoantigens for ROP-33
> INFO: Object size of neoantigens: 72 Kb
> INFO: Digesting neoantigens for ROP-32
> INFO: Object size of neoantigens: 26744 Kb
> INFO: Digesting neoantigens for ROP-37
> INFO: Object size of neoantigens: 30128 Kb
> INFO: Digesting neoantigens for ROP-36
> INFO: Object size of neoantigens: 23736 Kb
> INFO: Digesting neoantigens for ROP-34
> INFO: Object size of neoantigens: 33936 Kb
> INFO: Digesting neoantigens for ROP-38
> INFO: Object size of neoantigens: 23736 Kb
> INFO: Digesting neoantigens for ROP-132
> INFO: Object size of neoantigens: 14688 Kb
> INFO: Digesting neoantigens for ROP-18
> INFO: Object size of neoantigens: 111008 Kb
> INFO: Digesting neoantigens for ROP-19
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-54
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-57
> INFO: Object size of neoantigens: 7992 Kb
> INFO: Digesting neoantigens for ROP-56
> INFO: Object size of neoantigens: 54576 Kb
> INFO: Digesting neoantigens for ROP-51
> INFO: Object size of neoantigens: 33936 Kb
> INFO: Digesting neoantigens for ROP-50
> INFO: Object size of neoantigens: 4280 Kb
> INFO: Digesting neoantigens for ROP-53
> INFO: Object size of neoantigens: 48472 Kb
> INFO: Digesting neoantigens for ROP-78
> INFO: Object size of neoantigens: 30128 Kb
> INFO: Digesting neoantigens for ROP-11
> INFO: Object size of neoantigens: 23736 Kb
> INFO: Digesting neoantigens for ROP-76
> INFO: Object size of neoantigens: 48472 Kb
> INFO: Digesting neoantigens for ROP-75
> INFO: Object size of neoantigens: 69168 Kb
> INFO: Digesting neoantigens for ROP-12
> INFO: Object size of neoantigens: 72 Kb
> INFO: Digesting neoantigens for ROP-73
> INFO: Object size of neoantigens: 18680 Kb
> INFO: Digesting neoantigens for ROP-14
> INFO: Object size of neoantigens: 48472 Kb
> INFO: Digesting neoantigens for ROP-17
> INFO: Object size of neoantigens: 16568 Kb
> INFO: Digesting neoantigens for ROP-70
> INFO: Object size of neoantigens: 72 Kb
> INFO: Digesting neoantigens for ROP-1
> INFO: Object size of neoantigens: 54576 Kb
> INFO: Digesting neoantigens for ROP-121
> INFO: Object size of neoantigens: 7992 Kb
> INFO: Digesting neoantigens for ROP-122
> INFO: Object size of neoantigens: 124928 Kb
> INFO: Digesting neoantigens for ROP-109
> INFO: Object size of neoantigens: 43048 Kb
> INFO: Digesting neoantigens for ROP-125
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-126
> INFO: Object size of neoantigens: 72 Kb
> INFO: Digesting neoantigens for ROP-127
> INFO: Object size of neoantigens: 4856 Kb
> INFO: Digesting neoantigens for ROP-128
> INFO: Object size of neoantigens: 33936 Kb
> INFO: Digesting neoantigens for ROP-15
> INFO: Object size of neoantigens: 43048 Kb
> INFO: Digesting neoantigens for ROP-100
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-107
> INFO: Object size of neoantigens: 72 Kb
> INFO: Digesting neoantigens for ROP-105
> INFO: Object size of neoantigens: 33936 Kb
> INFO: Digesting neoantigens for ROP-83
> INFO: Object size of neoantigens: 2380496 Kb
> INFO: Digesting neoantigens for ROP-102
> INFO: Object size of neoantigens: 26744 Kb
> INFO: Digesting neoantigens for ROP-86
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-71
> INFO: Object size of neoantigens: 4856 Kb
> INFO: Digesting neoantigens for ROP-85
> INFO: Object size of neoantigens: 61440 Kb
> INFO: Digesting neoantigens for ROP-16
> INFO: Object size of neoantigens: 16568 Kb
> INFO: Digesting neoantigens for ROP-24
> INFO: Object size of neoantigens: 54576 Kb
> INFO: Digesting neoantigens for ROP-120
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-20
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-103
> INFO: Object size of neoantigens: 54576 Kb
> INFO: Digesting neoantigens for ROP-59
> INFO: Object size of neoantigens: 23736 Kb
> INFO: Digesting neoantigens for ROP-23
> INFO: Object size of neoantigens: 98632 Kb
> INFO: Digesting neoantigens for ROP-96
> INFO: Object size of neoantigens: 9032 Kb
> INFO: Digesting neoantigens for ROP-108
> INFO: Object size of neoantigens: 98632 Kb
> INFO: Digesting neoantigens for ROP-46
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-61
> INFO: Object size of neoantigens: 72 Kb
> INFO: Digesting neoantigens for ROP-44
> INFO: Object size of neoantigens: 33936 Kb
> INFO: Digesting neoantigens for ROP-123
> INFO: Object size of neoantigens: 43048 Kb
> INFO: Digesting neoantigens for ROP-42
> INFO: Object size of neoantigens: 26744 Kb
> INFO: Digesting neoantigens for ROP-65
> INFO: Object size of neoantigens: 87632 Kb
> INFO: Digesting neoantigens for ROP-68
> INFO: Object size of neoantigens: 72 Kb
> INFO: Digesting neoantigens for ROP-69
> INFO: Object size of neoantigens: 61440 Kb
> INFO: Digesting neoantigens for ROP-92
> INFO: Object size of neoantigens: 23736 Kb
> INFO: Digesting neoantigens for ROP-133
> INFO: Object size of neoantigens: 48472 Kb
> INFO: Digesting neoantigens for ROP-60
> INFO: Object size of neoantigens: 23736 Kb
> INFO: Digesting neoantigens for ROP-131
> INFO: Object size of neoantigens: 33936 Kb
> INFO: Digesting neoantigens for ROP-89
> INFO: Object size of neoantigens: 48472 Kb
> INFO: Digesting neoantigens for ROP-119
> INFO: Object size of neoantigens: 77856 Kb
> INFO: Digesting neoantigens for ROP-118
> INFO: Object size of neoantigens: 61440 Kb
> INFO: Digesting neoantigens for ROP-47
> INFO: Object size of neoantigens: 7992 Kb
> INFO: Digesting neoantigens for ROP-115
> INFO: Object size of neoantigens: 13016 Kb
> INFO: Digesting neoantigens for ROP-114
> INFO: Object size of neoantigens: 54576 Kb
> INFO: Digesting neoantigens for ROP-117
> INFO: Object size of neoantigens: 77856 Kb
> INFO: Digesting neoantigens for ROP-116
> INFO: Object size of neoantigens: 13016 Kb
> INFO: Digesting neoantigens for ROP-58
> INFO: Object size of neoantigens: 77856 Kb
> INFO: Digesting neoantigens for ROP-110
> INFO: Object size of neoantigens: 48472 Kb
> INFO: Digesting neoantigens for ROP-113
> INFO: Object size of neoantigens: 33936 Kb
> INFO: Digesting neoantigens for ROP-112
> INFO: Object size of neoantigens: 23736 Kb
> INFO: Digesting neoantigens for ROP-90
> INFO: Object size of neoantigens: 178032 Kb
> INFO: Digesting neoantigens for ROP-93
> INFO: Object size of neoantigens: 18680 Kb
> INFO: Digesting neoantigens for ROP-45
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-95
> INFO: Object size of neoantigens: 87632 Kb
> INFO: Digesting neoantigens for ROP-94
> INFO: Object size of neoantigens: 11528 Kb
> INFO: Digesting neoantigens for ROP-97
> INFO: Object size of neoantigens: 38224 Kb
> INFO: Digesting neoantigens for ROP-129
> INFO: Object size of neoantigens: 4856 Kb
> INFO: Digesting neoantigens for ROP-98
> INFO: Object size of neoantigens: 23736 Kb

Do you have any clues about what could be happening?

Thanks again,
Ramon
